name: Generate Attestation

on: [push]

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o myapp

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Generate attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: myapp