name: Generate Attestation

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.0'

    - name: Build
      run: go build -o myapp

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: myapp
